FROM python:3.13

# Переназначим рабочую папку
WORKDIR /app

# Скопировать только requirements (чтобы не пересобирать pip при каждом изменении кода)
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Скопировать весь оставшийся код
COPY . .

# Сделать entrypoint.sh исполняемым (если нужно)
RUN chmod +x entrypoint.sh

# Запуск при старте контейнера
ENTRYPOINT ["./entrypoint.sh"]
